apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: ClusterIP 
  ports:
    - name: "db-service"
      port: 5432  # what port service is listening on
      targetPort: 5432   # WAHT PORT TO FWD -  what port is db pod listening on
  selector:
    app: db  #to what pods to fwd