apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP 
  ports:
    - name: "redis-service"
      port: 6379  # what port service is listening on
      targetPort: 6379   # WAHT PORT TO FWD -  what port is redis pod listening on
  selector:
    app: redis  #to what pods to fwd