apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - name: "result-service"
      port: 80  # what port service is listening on
      targetPort: 80   # WAHT PORT TO FWD -  what port is result pod listening on
      nodePort: 31001
  selector:
    app: result  #to what pods to fwd